// Run against tools/mesa-preview.cjs. Requires Playwright in NODE_PATH.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
(async()=>{
  const server=spawn(process.execPath,[require('node:path').join(__dirname,'mesa-preview.cjs')],{env:{...process.env,MESA_PORT:'4319'},stdio:['ignore','pipe','inherit']});
  process.on('exit',()=>server.kill());
  await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);});
  const browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:4319');
  await page.getByRole('button',{name:'MESA',exact:true}).click();
  await page.getByRole('button',{name:'CRIAR CAMPANHA'}).click();
  await page.getByLabel('Nome da campanha').fill('O Observatório Vazio');
  await page.getByRole('button',{name:'Criar',exact:true}).click();
  await page.getByRole('button',{name:'Fichas',exact:true}).click();
  await page.getByRole('button',{name:'Nova ficha'}).click();
  await page.getByLabel('Personagem',{exact:true}).fill('Iria');
  await page.locator('[name=owner]').selectOption('2');
  await page.getByRole('button',{name:'Criar',exact:true}).click();
  await page.getByRole('button',{name:'Abrir ficha'}).click();
  await page.getByLabel('Classe / multiclasse').fill('Maga');
  await page.getByLabel('Nível',{exact:true}).fill('3');
  await page.getByRole('button',{name:'Salvar ficha'}).click();
  await page.getByRole('button',{name:'Compêndio',exact:true}).click();
  await page.getByRole('button',{name:'Novo conteúdo'}).click();
  await page.getByLabel('Nome',{exact:true}).fill('Centelha da campanha');
  await page.getByLabel('Descrição — conteúdo próprio ou autorizado').fill('Uma luz criada pelo GM para esta campanha.');
  await page.getByLabel('Publicar para os jogadores').check();
  await page.getByRole('button',{name:'Salvar',exact:true}).click();
  await page.getByRole('heading',{name:'Centelha da campanha'}).waitFor();
  await page.getByRole('button',{name:'Preparação',exact:true}).click();
  await page.getByRole('button',{name:'Novo mapa'}).click();
  await page.getByLabel('Nome',{exact:true}).fill('Câmara superior');
  await page.getByRole('button',{name:'Criar',exact:true}).click();
  await page.getByRole('button',{name:'Importar imagem'}).click();
  await page.locator('input[type=file]').setInputFiles({name:'mapa.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aCr8AAAAASUVORK5CYII=','base64')});
  await page.getByRole('button',{name:'Importar',exact:true}).click();
  await page.getByRole('button',{name:'Abrir',exact:true}).click();
  await page.locator('.mesa-map>img').waitFor();
  await page.getByRole('button',{name:'Adicionar peça'}).click();
  await page.locator('[name=sheet]').selectOption({label:'Iria'});
  await page.getByLabel('Oculta aos jogadores').uncheck();
  await page.getByRole('button',{name:'Adicionar',exact:true}).last().click();
  await page.getByRole('button',{name:'Revelar',exact:true}).click();
  await page.getByRole('button',{name:'Adicionar',exact:true}).click();
  await page.getByLabel('Participante').fill('Iria');
  await page.getByLabel('Resultado').fill('19');
  await page.getByRole('button',{name:'Adicionar',exact:true}).last().click();
  await page.getByRole('button',{name:'ROLAR',exact:true}).click();
  await page.getByText(/1d20 =/).waitFor();
  const token=page.getByRole('button',{name:'Iria',exact:true});
  const box=await page.locator('.mesa-map').boundingBox();
  await token.hover();await page.mouse.down();await page.mouse.move(box.x+box.width*.45,box.y+box.height*.65);await page.mouse.up();
  await page.waitForTimeout(400);
  const pos=await token.evaluate(el=>({left:el.style.left,top:el.style.top}));
  assert.ok(parseFloat(pos.left)>40);assert.ok(parseFloat(pos.top)>60);
  await page.screenshot({path:'/tmp/mesa-v1-desktop.png',fullPage:true});
  const player=await browser.newPage({viewport:{width:1280,height:900}});player.on('pageerror',e=>errors.push(e.message));
  await player.goto('http://127.0.0.1:4319');await player.getByRole('combobox').selectOption('2');await player.getByRole('button',{name:'MESA',exact:true}).click();
  await player.getByRole('heading',{name:'Câmara superior'}).waitFor();
  assert.equal(await player.getByRole('button',{name:'Preparação',exact:true}).count(),0);
  await player.getByRole('button',{name:'Fichas',exact:true}).click();await player.getByRole('button',{name:'Abrir ficha'}).click();
  assert.equal(await player.getByLabel('Classe / multiclasse').inputValue(),'Maga');
  await player.getByRole('button',{name:'Fechar',exact:true}).last().click();
  await player.setViewportSize({width:720,height:700});
  assert.equal(await player.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  assert.deepEqual(errors,[]);
  console.log('UI passed: setup, sheets, compendium, image import, scenes, tokens, dice, initiative, player view, narrow layout.');
  await browser.close();
  server.kill();
})().catch(e=>{console.error(e);process.exit(1)});
